# name: Deploy FastAPI to AWS Lambda

# on:
#   push:
#     branches:
#       - main  # Trigger the action on push to main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout the repository
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8

#     - name: Set up AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-west-2  # Replace with your region if different

#     - name: Install dependencies
#       run: |
#         python -m venv venv
#         source venv/bin/activate
#         pip install -r app/requirements.txt
#         pip install aws-sam-cli

#     - name: Build and Deploy with SAM
#       run: |
#         sam build
#         sam deploy \
#           --stack-name fastapi-stack \
#           --capabilities CAPABILITY_IAM \
#           --region us-west-2 \
#           --resolve-s3

#     - name: Post Deployment Success Message
# #       run: echo "✅ FastAPI deployed successfully to AWS Lambda!"
# name: CI/CD for FastAPI on Lambda

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Python 3.8
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r app/requirements.txt

#     - name: Build SAM Application
#       run: |
#         curl -Lo /tmp/aws-sam-cli-linux-x86_64.tar.gz https://github.com/aws/aws-sam-cli/releases/download/v1.51.0/aws-sam-cli-linux-x86_64.tar.gz
#         sudo mkdir -p /usr/local/aws-sam-cli
#         sudo tar -xvzf /tmp/aws-sam-cli-linux-x86_64.tar.gz -C /usr/local/aws-sam-cli
#         sudo /usr/local/aws-sam-cli/install
#         sam build

#     - name: Deploy SAM Application
#       run: |
#         sam deploy --no-confirm-changeset --stack-name fastapi-lambda-stack --capabilities CAPABILITY_IAM
#       env:
#         AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_DEFAULT_REGION: us-east-1
name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main  # Trigger the action on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout the repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.8
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Step 3: Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Adjust to your region if different

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r app/requirements.txt

    # Step 5: Install AWS SAM CLI using official repository (Ubuntu)
    - name: Install AWS SAM CLI
      run: |
        curl -fsSL https://s3.amazonaws.com/aws-sam-cli-releases/latest/install.sh | sudo bash

    # Step 6: Build and Deploy the SAM Application
    - name: Build and Deploy with SAM
      run: |
        sam build
        sam deploy \
          --stack-name fastapi-stack \
          --capabilities CAPABILITY_IAM \
          --region us-west-2 \
          --no-confirm-changeset \
          --resolve-s3

    # Step 7: Post Deployment Success Message
    - name: Post Deployment Success Message
      run: echo "✅ FastAPI deployed successfully to AWS Lambda!"
