name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Replace with your desired region

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r app/requirements.txt
        pip install aws-sam-cli

    - name: Build and Deploy with SAM
      run: |
        sam build
        sam deploy --no-confirm-changeset --stack-name fastapi-stack --capabilities CAPABILITY_IAM

    - name: Post Deployment Success Message
      run: echo "FastAPI deployed successfully!"
